"""add_spk_updated_at_column_to_fix_prod

Revision ID: 30b6fc8fc25e
Revises: 5fba2d7adff0
Create Date: 2025-06-05 12:04:08.233530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b6fc8fc25e'
down_revision: Union[str, None] = '5fba2d7adff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
