"""uuid

Revision ID: 32980ebf4f0b
Revises: b1f2ff5835f8
Create Date: 2025-05-30 14:29:13.847441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32980ebf4f0b'
down_revision: Union[str, None] = 'b1f2ff5835f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('uuid', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=True)
    op.alter_column('users', 'public_key',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=191),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_key',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=False)
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.drop_column('files', 'uuid')
    # ### end Alembic commands ###
