"""switch to timezone aware timestamps

Revision ID: 49b0ea6601d9
Revises: a8807550dc9f
Create Date: 2025-06-03 22:57:09.863176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b0ea6601d9'
down_revision: Union[str, None] = 'a8807550dc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
