"""switch to timezone aware timestamps

Revision ID: 506c46e6d55c
Revises: 8888eb0da84b
Create Date: 2025-06-03 23:47:09.094797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506c46e6d55c'
down_revision: Union[str, None] = '8888eb0da84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Get all tables
    tables = inspector.get_table_names()
    
    for table in tables:
        # Get all columns for the table
        columns = inspector.get_columns(table)
        
        # Find datetime columns that need timezone
        for column in columns:
            if isinstance(column['type'], sa.DateTime) and not column['type'].timezone:
                # Alter the column to add timezone
                op.alter_column(
                    table,
                    column['name'],
                    type_=sa.DateTime(timezone=True),
                    existing_type=sa.DateTime(),
                    existing_nullable=column['nullable']
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Get all tables
    tables = inspector.get_table_names()
    
    for table in tables:
        # Get all columns for the table
        columns = inspector.get_columns(table)
        
        # Find datetime columns with timezone
        for column in columns:
            if isinstance(column['type'], sa.DateTime) and column['type'].timezone:
                # Alter the column to remove timezone
                op.alter_column(
                    table,
                    column['name'],
                    type_=sa.DateTime(),
                    existing_type=sa.DateTime(timezone=True),
                    existing_nullable=column['nullable']
                )
    # ### end Alembic commands ###
