"""description

Revision ID: 6ccf9986b9f7
Revises: 27970bd5f22c
Create Date: 2025-06-01 21:58:01.984838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ccf9986b9f7'
down_revision: Union[str, None] = '27970bd5f22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_key',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.String(length=191),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'public_key',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###
