"""spk and signature to users

Revision ID: 6e7100f43d45
Revises: 4b1f4a9a3809
Create Date: 2025-06-02 19:10:29.342340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7100f43d45'
down_revision: Union[str, None] = '4b1f4a9a3809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'spk' not in columns:
        op.add_column('users', sa.Column('spk', sa.BLOB(), nullable=False))
    if 'spk_signature' not in columns:
        op.add_column('users', sa.Column('spk_signature', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spk_signature')
    op.drop_column('users', 'spk')
    # ### end Alembic commands ###
