"""otpk updated at

Revision ID: 8888eb0da84b
Revises: a5ef8f231080
Create Date: 2025-06-03 00:12:05.522869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8888eb0da84b'
down_revision: Union[str, None] = 'a5ef8f231080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('one_time_pre_keys')]
    
    if 'updated_at' not in columns:
        op.add_column('one_time_pre_keys', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('one_time_pre_keys', 'updated_at')
    # ### end Alembic commands ###
