"""blob to string keys

Revision ID: a5ef8f231080
Revises: ecb8d6ff1485
Create Date: 2025-06-02 22:29:22.859400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ef8f231080'
down_revision: Union[str, None] = 'ecb8d6ff1485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_permissions', 'encryption_key',
               existing_type=sa.BLOB(),
               type_=sa.String(length=191),
               existing_nullable=False)
    op.alter_column('file_permissions', 'ephemeral_key',
               existing_type=sa.BLOB(),
               type_=sa.String(length=191),
               existing_nullable=False)
    op.alter_column('one_time_pre_keys', 'key',
               existing_type=sa.BLOB(),
               type_=sa.String(length=191),
               existing_nullable=False)
    op.alter_column('users', 'spk',
               existing_type=sa.BLOB(),
               type_=sa.String(length=191),
               existing_nullable=False)
    op.alter_column('users', 'spk_signature',
               existing_type=sa.BLOB(),
               type_=sa.String(length=191),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'spk_signature',
               existing_type=sa.String(length=191),
               type_=sa.BLOB(),
               existing_nullable=False)
    op.alter_column('users', 'spk',
               existing_type=sa.String(length=191),
               type_=sa.BLOB(),
               existing_nullable=False)
    op.alter_column('one_time_pre_keys', 'key',
               existing_type=sa.String(length=191),
               type_=sa.BLOB(),
               existing_nullable=False)
    op.alter_column('file_permissions', 'ephemeral_key',
               existing_type=sa.String(length=191),
               type_=sa.BLOB(),
               existing_nullable=False)
    op.alter_column('file_permissions', 'encryption_key',
               existing_type=sa.String(length=191),
               type_=sa.BLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
