"""add spk_updated_at field

Revision ID: a8807550dc9f
Revises: 8888eb0da84b
Create Date: 2025-06-03 22:38:20.887410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8807550dc9f'
down_revision: Union[str, None] = '8888eb0da84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spk_updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spk_updated_at')
    # ### end Alembic commands ###
